allowBuilds:
  esbuild: true
  msw: true
minimumReleaseAgeExclude:
  - "@orval/angular@8.22.0"
  - "@orval/axios@8.22.0"
  - "@orval/core@8.22.0"
  - "@orval/effect@8.22.0"
  - "@orval/fetch@8.22.0"
  - "@orval/hono@8.22.0"
  - "@orval/mcp@8.22.0"
  - "@orval/mock@8.22.0"
  - "@orval/query@8.22.0"
  - "@orval/solid-start@8.22.0"
  - "@orval/swr@8.22.0"
  - "@orval/zod@8.22.0"
  - orval@8.22.0
